name: Convert Markdown to PDF

on:
  push:
    paths:
      - 'src/**/*.md'
  pull_request:
    paths:
      - 'src/**/*.md'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7
      
      - name: Set up Pandoc
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc

      - name: Run conversion script
        run: |
          chmod +x src/convert_md_to_pdf.sh
          src/convert_md_to_pdf.sh
