name: Convert Markdown to PDF

on:
  push:
    branches:
      - '**'
  pull_request:
    paths:
      - 'src/**/*.md'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc pandoc-citeproc texlive-latex-recommended texlive-latex-extra texlive-xetex texlive-luatex

      - name: Run conversion script
        run: |
          cd src
          chmod +x convert_md_to_pdf.sh
          ./convert_md_to_pdf.sh

      - name: Commit PDF files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "Add converted PDF files"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
