name: Convert Markdown to PDF

on:
  push:
    branches:
      - '**'
  pull_request:
    paths:
      - 'src/**/*.md'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc pandoc-citeproc texlive-latex-recommended texlive-latex-extra texlive-xetex texlive-luatex

      - name: Run conversion script
        run: |
          cd src
          chmod +x convert_md_to_pdf.sh
          ./convert_md_to_pdf.sh
